### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by ouasamine** [MudasirSherwani/To-Do-list-with-webpack#2]
### Hi @MudasirSherwani the team members reviewed your code and they had the following observations:

- Your code is well organised well done on that 👍🏽 
-  We believe that using createElement method is easier and better than using innerHTML as you did in line [46](https://github.com/MudasirSherwani/To-Do-list-with-webpack/pull/1/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R47).

Otherwise, you have done a very good job ✔️

**Comment by MudasirSherwani** [comment]
Hi @ouasamine :wave: 
Hi All Morning session team members :wave: 
I'm very thankful to you all for such a precious review. I will try to make it better according to your suggestions.
